spring:
  application:
    name: product-service
  profiles:
    active: local # 19083으로 서버실행, 주석처리하면 19093
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

# POST http://localhost:19083/actuator/refresh -> post로 요청보내야하고 데이터는 비운상태로 요청
management:
  endpoints:
    web:
      exposure:
        include: refresh
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0 # 기본값 0.1

message: "default message"

